# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('stock_minimo', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
