# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarea', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservastock',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tarea.Tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='reservastock',
            unique_together=set([('producto', 'tarea')]),
        ),
    ]
