# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_reservastock_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.AddField(
            model_name='producto',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reservastock',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
