# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20171101_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set([('nombre', 'marca')]),
        ),
    ]
