# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 17:01
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20171030_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservastock',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
