# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20171125_2145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set([('nombre', 'marca')]),
        ),
    ]
