# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20170929_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='producto.Producto')),
            ],
        ),
    ]
