# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 23:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20171102_1854'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reservastock',
            managers=[
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='reservastock',
            old_name='activa',
            new_name='activo',
        ),
    ]
