# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20171125_2226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set([]),
        ),
    ]
