# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20171124_2329'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='producto',
            managers=[
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
