# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20171124_2338'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='producto',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='reservastock',
            managers=[
            ],
        ),
    ]
