# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervicio',
            name='activo',
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
