# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_doc', models.CharField(choices=[('DU', 'DNI'), ('CL', 'CUIL'), ('CT', 'CUIT')], default='DU', max_length=2)),
                ('doc', models.CharField(max_length=20, unique=True)),
                ('domicilio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_doc', models.CharField(choices=[('DU', 'DNI'), ('CL', 'CUIL'), ('CT', 'CUIT')], default='DU', max_length=2)),
                ('doc', models.CharField(max_length=20, unique=True)),
                ('domicilio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
