# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_doc', models.CharField(choices=[('DU', 'DNI'), ('CL', 'CUIL'), ('CT', 'CUIT')], default='DU', max_length=2)),
                ('doc', models.CharField(max_length=20, unique=True)),
                ('domicilio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Rol')),
            ],
            bases=('persona.rol',),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('rol_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.Rol')),
            ],
            options={
                'permissions': (('p1', 'Permiso Tecnico'),),
            },
            bases=('persona.rol',),
        ),
        migrations.AddField(
            model_name='rol',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
