# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_remove_rol_rolname'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
