# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_gerente_jefetaller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnico',
            options={},
        ),
        migrations.AddField(
            model_name='rol',
            name='rolname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
