# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20171204_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='activo',
        ),
        migrations.AddField(
            model_name='persona',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
