# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20171029_1346'),
        ('persona', '0008_auto_20171028_2207'),
    ]

    operations = [
    ]
