# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primer_login',
            field=models.BooleanField(default=True),
        ),
    ]
