# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
