# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
