# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
