# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('rubro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='rubro.Rubro'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='rubro.Tarea'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='servicio.TipoServicio'),
        ),
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together=set([('tarea', 'tipo_servicio')]),
        ),
    ]
