# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rubro', '0002_auto_20171014_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='rubro',
        ),
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='tipo_servicio',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
