# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0003_auto_20170914_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_serie', models.IntegerField(unique=True)),
                ('decripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Cliente')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orden.Equipo')),
            ],
        ),
    ]
