# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_auto_20171101_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
