# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orden', '0002_auto_20170928_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'estado'), (0, 'creada'), (0, 'diagnosticada'), (0, 'aceptada'), (0, 'cerrada')])),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='decripcion',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='orden',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='persona.Cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='orden.Equipo'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='rubro.Rubro'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='persona.Tecnico'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='servicio.TipoServicio'),
        ),
        migrations.CreateModel(
            name='Aceptada',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orden.Estado')),
            ],
            bases=('orden.estado',),
        ),
        migrations.CreateModel(
            name='Cerrada',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orden.Estado')),
            ],
            bases=('orden.estado',),
        ),
        migrations.CreateModel(
            name='Creada',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orden.Estado')),
            ],
            bases=('orden.estado',),
        ),
        migrations.CreateModel(
            name='Diagnosticada',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orden.Estado')),
            ],
            bases=('orden.estado',),
        ),
        migrations.AddField(
            model_name='estado',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='orden.Orden'),
        ),
        migrations.AddField(
            model_name='estado',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
