# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0002_auto_20171029_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'creada'), (2, 'diagnosticada'), (5, 'cancelada'), (3, 'aceptada'), (4, 'cerrada')]),
        ),
    ]
