# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubro', '0003_auto_20171015_0507'),
        ('orden', '0003_auto_20171030_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rubro.Rubro'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'creada'), (2, 'diagnosticada'), (4, 'cerrada'), (5, 'cancelada'), (3, 'aceptada')]),
        ),
    ]
