# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_auto_20171030_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='tareas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea.Tarea'),
        ),
    ]
