# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_auto_20171204_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='activo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
