# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_auto_20171101_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
