# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_auto_20171030_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='tareas',
        ),
    ]
