# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_auto_20171103_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
