# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0004_orden_precio_final'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
