# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
        ('orden', '0004_auto_20171025_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='tareas',
        ),
        migrations.AddField(
            model_name='diagnosticada',
            name='tareas',
            field=models.ManyToManyField(to='tarea.Tarea'),
        ),
    ]
