# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_tarea_orden'),
        ('orden', '0005_auto_20171030_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='tarea',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tarea.Tarea'),
            preserve_default=False,
        ),
    ]
