# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0005_orden_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
