# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0005_auto_20171025_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticada',
            name='tareas',
        ),
        migrations.AddField(
            model_name='estado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'creada'), (2, 'diagnosticada'), (3, 'aceptada'), (4, 'cerrada')], default=0),
            preserve_default=False,
        ),
    ]
