# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0005_auto_20171130_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='precio_final',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
