# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
        ('orden', '0006_auto_20171025_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='tareas',
            field=models.ManyToManyField(to='tarea.Tarea'),
        ),
    ]
