# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 15:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0006_auto_20171201_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
