# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0006_detalleorden_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='tarea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tarea.Tarea'),
        ),
    ]
