# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0007_estado_tareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelada',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orden.Estado')),
                ('motivo', models.CharField(max_length=140)),
            ],
            bases=('orden.estado',),
        ),
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'creada'), (2, 'diagnosticada'), (3, 'aceptada'), (4, 'cerrada'), (5, 'cancelada')]),
        ),
    ]
