# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-15 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicio', '0001_initial'),
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='tarea.Tarea')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='servicio.TipoServicio')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tarifa',
            unique_together=set([('tarea', 'tipo_servicio')]),
        ),
    ]
