# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadotarea',
            name='tarea',
        ),
        migrations.RemoveField(
            model_name='estadotarea',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tareabloqueada',
            name='estadotarea_ptr',
        ),
        migrations.RemoveField(
            model_name='tareacancelada',
            name='estadotarea_ptr',
        ),
        migrations.RemoveField(
            model_name='tareapendiente',
            name='estadotarea_ptr',
        ),
        migrations.RemoveField(
            model_name='tareapresupuestada',
            name='estadotarea_ptr',
        ),
        migrations.DeleteModel(
            name='EstadoTarea',
        ),
        migrations.DeleteModel(
            name='TareaBloqueada',
        ),
        migrations.DeleteModel(
            name='TareaCancelada',
        ),
        migrations.DeleteModel(
            name='TareaPendiente',
        ),
        migrations.DeleteModel(
            name='TareaPresupuestada',
        ),
    ]
