# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
