# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0005_auto_20171030_0742'),
        ('tarea', '0002_estadotarea_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='orden.Estado'),
        ),
    ]
