# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_auto_20171101_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='orden',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='orden.Orden'),
            preserve_default=False,
        ),
    ]
