# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 21:03
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20170929_1348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarea', '0003_auto_20171029_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_tarea', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'estado')])),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.CreateModel(
            name='TareaCancelada',
            fields=[
                ('estadotarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarea.EstadoTarea')),
            ],
            bases=('tarea.estadotarea',),
        ),
        migrations.CreateModel(
            name='TareaEsperaRepuestos',
            fields=[
                ('estadotarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarea.EstadoTarea')),
            ],
            bases=('tarea.estadotarea',),
        ),
        migrations.CreateModel(
            name='TareaPendiente',
            fields=[
                ('estadotarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarea.EstadoTarea')),
            ],
            bases=('tarea.estadotarea',),
        ),
        migrations.CreateModel(
            name='TareaPresupuestada',
            fields=[
                ('estadotarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarea.EstadoTarea')),
            ],
            bases=('tarea.estadotarea',),
        ),
        migrations.AddField(
            model_name='estadotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='tarea.Tarea'),
        ),
        migrations.AddField(
            model_name='estadotarea',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
