# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_tarea_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='orden',
            new_name='estado_orden',
        ),
    ]
