# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0003_auto_20171101_0229'),
        ('tarea', '0004_auto_20171102_1947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarea',
            unique_together=set([('tipo_tarea', 'orden')]),
        ),
    ]
