# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0004_auto_20171204_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipotarea',
            name='activo',
        ),
        migrations.AddField(
            model_name='estadotarea',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='observaciontarea',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tipotarea',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
