# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0004_auto_20171029_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadotarea',
            name='tarifa_tarea',
        ),
        migrations.AddField(
            model_name='tarea',
            name='observacion',
            field=models.CharField(default='-', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estadotarea',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'tareapresupuestada'), (2, 'tareaesperarepuestos'), (3, 'tareapendiente'), (4, 'tareacancelada')]),
        ),
    ]
