# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 06:02
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0005_auto_20171205_0355'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tareacancelada',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tareapendiente',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tareapresupuestada',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tarearealizada',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
