# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0005_auto_20171029_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaRealizada',
            fields=[
                ('estadotarea_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarea.EstadoTarea')),
            ],
            bases=('tarea.estadotarea',),
        ),
        migrations.AlterField(
            model_name='estadotarea',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'tareapresupuestada'), (2, 'tareaesperarepuestos'), (3, 'tareapendiente'), (4, 'tarearealizada'), (5, 'tareacancelada')]),
        ),
    ]
