# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0005_auto_20171102_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='observacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo_tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tarea.TipoTarea'),
        ),
    ]
