# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0006_auto_20171029_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.ReservaStock'),
        ),
    ]
