# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0006_auto_20171205_0602'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tareacancelada',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tareapendiente',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tareapresupuestada',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tarearealizada',
            managers=[
            ],
        ),
    ]
