# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0007_auto_20171029_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadotarea',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'estado'), (1, 'tareapresupuestada'), (2, 'tareaesperarepuestos'), (5, 'tareacancelada'), (3, 'tareapendiente'), (4, 'tarearealizada')]),
        ),
    ]
